### ISSUE TITLE
Get all three architecture variations working in T5X

### ISSUE THREAD

**Issue by slippylolo** [bigscience-workshop/t5x#2]
## Description

We need to confirm we can get all three architectural variations working in T5X: encoder-decoder, prefix LM, and decoder-only. We should confirm they all work with data for CLM/MLM, and document thoroughly our configurations for reuse later. 

This can be done on the TPUv3-128 we already have, no need for the v4s. 

## Action items
- [ ] Get encoder-decoder working for CLM/MLM & documented;
- [ ] Get decoder-only working for CLM/MLM & documented;
- [ ] Get prefix LM working for CLM/MLM & documented.

**Comment by TevenLeScao** [comment]
I'll try to do this with C4 while we're processing the pile
