### ISSUE TITLE
Checkpoint Links

### ISSUE THREAD

**Issue by cfoster0** [bigscience-workshop/t5x#25]
Reminder that this repo still is still awaiting links to the checkpoints accompanying the architecture objective paper. 

> // TODO (@thomasw21): Summary + link to paper + link to checkpoints.

**Comment by thomasw21** [comment]
Thanks for the reminder, we'll push to have it available ASAP.

**Comment by thomasw21** [comment]
Partial set of checkpoints (essentially the ones mentioned in the main paper) are now documented: 25385c0eb07409e4d66213d31bb92217f005da94

Sorry for the long wait! Let me know if you're interested in specific checkpoints that are not listed.

Closing as this should be resolved now.
